# 设置服务器端口
server:
  port: 88
  servlet:
    context-path: "/abc"
    encoding:
      charset: UTF-8

# 伪造一个数据
username: wangzhanf
# 爱好
hobby:
  - 足球
  - 篮球
  - 乒乓球

Person:
  name: guest
  age: 18
  salary: 234.56


conndb:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3331/ele_se?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: root
  password: 111111